//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistant.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assistant.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assistant ChatLog pour GTA World France.
        ///
        ///Version installée: {0} {1}
        ///Chemin des ressources: {2}.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtre avancé.
        /// </summary>
        internal static string AdvancedFilter {
            get {
                return ResourceManager.GetString("AdvancedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à parce que les &quot;{0}&quot; chemins already existent déjà..
        /// </summary>
        internal static string AlreadyExistingDirectoriesWarning {
            get {
                return ResourceManager.GetString("AlreadyExistingDirectoriesWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la tentative de désactivation de la fonction de démarrage automatique..
        /// </summary>
        internal static string AutoStartDisableError {
            get {
                return ResourceManager.GetString("AutoStartDisableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la tentative d&apos;activation de la fonction de démarrage automatique..
        /// </summary>
        internal static string AutoStartEnableError {
            get {
                return ResourceManager.GetString("AutoStartEnableError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette fonctionnalité cessera de fonctionner si vous supprimez ou déplacez l&apos;analyseur vers un autre emplacement..
        /// </summary>
        internal static string AutoStartWarning {
            get {
                return ResourceManager.GetString("AutoStartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la tentative d&apos;enregistrement automatique du chatlog.
        ///
        ///Assurez-vous d&apos;avoir choisi un répertoire non système pour votre chemin de sauvegarde..
        /// </summary>
        internal static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors du déplacement des fichiers de sauvegarde vers le nouveau répertoire..
        /// </summary>
        internal static string BackupMoveError {
            get {
                return ResourceManager.GetString("BackupMoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde automatique: {0}.
        /// </summary>
        internal static string BackupStatus {
            get {
                return ResourceManager.GetString("BackupStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde automatique a été désactivée, veuillez la configurer à nouveau si vous souhaitez l&apos;utiliser..
        /// </summary>
        internal static string BackupTurnedOff {
            get {
                return ResourceManager.GetString("BackupTurnedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La fonction de sauvegarde automatique sera désactivée lorsque la boîte de dialogue des paramètres est ouverte et les nouveaux paramètres ne seront appliqués qu&apos;une fois que vous aurez fermé la boîte de dialogue des paramètres.
        ///
        ///Voulez-vous continuer?.
        /// </summary>
        internal static string BackupWillBeOff {
            get {
                return ResourceManager.GetString("BackupWillBeOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir un répertoire non racine pour votre emplacement de répertoire de sauvegarde..
        /// </summary>
        internal static string BadBackupPath {
            get {
                return ResourceManager.GetString("BadBackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir un emplacement de sauvegarde valide ou désactiver la sauvegarde automatique..
        /// </summary>
        internal static string BadBackupPathSave {
            get {
                return ResourceManager.GetString("BadBackupPathSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir un répertoire non racine pour votre emplacement de répertoire RAGEMP..
        /// </summary>
        internal static string BadDirectoryPath {
            get {
                return ResourceManager.GetString("BadDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Beta.
        /// </summary>
        internal static string Beta {
            get {
                return ResourceManager.GetString("Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à b.
        /// </summary>
        internal static string BetaShort {
            get {
                return ResourceManager.GetString("BetaShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0} caractères et {1} lignes.
        /// </summary>
        internal static string CharacterCounter {
            get {
                return ResourceManager.GetString("CharacterCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Heure actuelle: {0}.
        /// </summary>
        internal static string CurrentTime {
            get {
                return ResourceManager.GetString("CurrentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le logiciel a trouvé automatiquement votre répertoire RAGEMP à {0}
        ///
        ///Veuillez rechercher manuellement le chemin correct si celui-ci est incorrect ou si vous avez plusieurs installations RAGEMP..
        /// </summary>
        internal static string DirectoryFinder {
            get {
                return ResourceManager.GetString("DirectoryFinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la tentative de recherche automatique de l&apos;emplacement de votre répertoire RAGEMP, veuillez le rechercher manuellement..
        /// </summary>
        internal static string DirectoryFinderError {
            get {
                return ResourceManager.GetString("DirectoryFinderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de détecter le chemin de votre répertoire RAGEMP, veuillez le rechercher manuellement..
        /// </summary>
        internal static string DirectoryFinderNotFound {
            get {
                return ResourceManager.GetString("DirectoryFinderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information (Première fois).
        /// </summary>
        internal static string DirectoryFinderTitle {
            get {
                return ResourceManager.GetString("DirectoryFinderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OFF.
        /// </summary>
        internal static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ON.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Erreur.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://face-fr.gta.world/.
        /// </summary>
        internal static string FacebrowserLink {
            get {
                return ResourceManager.GetString("FacebrowserLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://forum.gta.world/en/index.php?/topic/7690-chat-logs/.
        /// </summary>
        internal static string FeatureShowcaseLink {
            get {
                return ResourceManager.GetString("FeatureShowcaseLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la tentative de suppression du fichier..
        /// </summary>
        internal static string FileDeleteError {
            get {
                return ResourceManager.GetString("FileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez avoir qu&apos;un seul mot, numéro ou paire de noms valide sur chaque ligne si vous souhaitez filtrer votre journal de discussion.
        ///Exemple: Bateau, 500 $, John, John Doe ou John_Doe.
        /// </summary>
        internal static string FilterHint {
            get {
                return ResourceManager.GetString("FilterHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun résultat.
        ///
        ///Assurez-vous de n&apos;avoir qu&apos;un seul mot, numéro ou paire de noms valide sur chaque ligne.
        ///Exemple: Bateau, 500 $, John, John Doe ou John_Doe.
        /// </summary>
        internal static string FilterHintNoMatches {
            get {
                return ResourceManager.GetString("FilterHintNoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un ou plusieurs mots ont été ignorés lors de l&apos;opération de filtrage car ils ne sont pas dans un format valide.
        ///
        ///Assurez-vous de n&apos;avoir qu&apos;un seul mot, numéro ou paire de noms valide sur chaque ligne.
        ///Exemple: Bateau, 500 $, John, John Doe ou John_Doe.
        /// </summary>
        internal static string FilterHintSkipped {
            get {
                return ResourceManager.GetString("FilterHintSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chatlog {0} chargé {1}.
        /// </summary>
        internal static string FilterLogStatus {
            get {
                return ResourceManager.GetString("FilterLogStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la lecture du fichier sélectionné..
        /// </summary>
        internal static string FilterReadError {
            get {
                return ResourceManager.GetString("FilterReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://forum-fr.gta.world/.
        /// </summary>
        internal static string ForumsLink {
            get {
                return ResourceManager.GetString("ForumsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegardez automatiquement le journal du chat pendant que le jeu est en cours d&apos;exécution (tous les {0} {1}).
        /// </summary>
        internal static string IntervalHint {
            get {
                return ResourceManager.GetString("IntervalHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}. (recommendé).
        /// </summary>
        internal static string IntervalRecommended {
            get {
                return ResourceManager.GetString("IntervalRecommended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chemin du répertoire RAGEMP non valide..
        /// </summary>
        internal static string InvalidDirectoryPath {
            get {
                return ResourceManager.GetString("InvalidDirectoryPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir un emplacement de répertoire RAGEMP valide avant d&apos;essayer d&apos;activer la sauvegarde automatique..
        /// </summary>
        internal static string InvalidDirectoryPathBackup {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez choisir un emplacement de répertoire RAGEMP valide avant d&apos;essayer de filtrer votre journal de discussion..
        /// </summary>
        internal static string InvalidDirectoryPathFilter {
            get {
                return ResourceManager.GetString("InvalidDirectoryPathFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La langue choisie sera utilisée pour extraire le journal de discussion du serveur approprié.
        ///
        ///Cela signifie que si vous avez choisi l&apos;anglais, vous ne pourrez analyser que le journal de discussion généré à partir du serveur anglais. Vous devrez changer la langue de l&apos;application si vous souhaitez analyser d&apos;autres journaux de discussion..
        /// </summary>
        internal static string LanguageInfo {
            get {
                return ResourceManager.GetString("LanguageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  à {0}.
        /// </summary>
        internal static string LoadedAt {
            get {
                return ResourceManager.GetString("LoadedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 164.132.206.209_22007.
        /// </summary>
        internal static string MainIP {
            get {
                return ResourceManager.GetString("MainIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La fermeture de l&apos;analyseur empêchera les sauvegardes automatiques de se produire.
        ///
        ///Souhaitez-vous plutôt réduire l&apos;analyseur dans la barre d&apos;état système?.
        /// </summary>
        internal static string MinimizeInsteadOfClose {
            get {
                return ResourceManager.GetString("MinimizeInsteadOfClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minutes.
        /// </summary>
        internal static string MinutePlural {
            get {
                return ResourceManager.GetString("MinutePlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à minute.
        /// </summary>
        internal static string MinuteSingular {
            get {
                return ResourceManager.GetString("MinuteSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souhaitez-vous déplacer tous vos fichiers de sauvegarde existants vers le nouveau répertoire?.
        /// </summary>
        internal static string MoveBackups {
            get {
                return ResourceManager.GetString("MoveBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plusieurs répertoires de ressources GTA World ont été trouvés. Il est conseillé d&apos;utiliser une seule adresse IP pour vous connecter au serveur et supprimer l&apos;autre répertoire de ressources.
        ///
        ///Conservez &quot;{0}&quot; ou &quot;{1}&quot;..
        /// </summary>
        internal static string MultipleChatLogs {
            get {
                return ResourceManager.GetString("MultipleChatLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  non.
        /// </summary>
        internal static string Negation {
            get {
                return ResourceManager.GetString("Negation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible de trouver le journal de discussion de GTA World..
        /// </summary>
        internal static string NoChatLog {
            get {
                return ResourceManager.GetString("NoChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez pas encore chargé de journal de discussion..
        /// </summary>
        internal static string NoChatLogLoaded {
            get {
                return ResourceManager.GetString("NoChatLogLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune mise à jour n&apos;a pu être trouvée.
        ///Essayez de vérifier votre connexion Internet ou d&apos;augmenter le délai de vérification des mises à jour dans la fenêtre des paramètres.
        ///
        ///Version installée: {0}.
        /// </summary>
        internal static string NoInternet {
            get {
                return ResourceManager.GetString("NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez encore rien filtré..
        /// </summary>
        internal static string NothingFiltered {
            get {
                return ResourceManager.GetString("NothingFiltered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N&apos;a déplacé aucun répertoire vers le nouvel emplacement.
        /// </summary>
        internal static string NothingMovedWarning {
            get {
                return ResourceManager.GetString("NothingMovedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez encore rien analysé..
        /// </summary>
        internal static string NothingParsed {
            get {
                return ResourceManager.GetString("NothingParsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez saisi aucun mot pour filtrer.
        ///
        ///Utilisez le filtre simple si vous ne souhaitez pas filtrer les mots..
        /// </summary>
        internal static string NoWordsToFilter {
            get {
                return ResourceManager.GetString("NoWordsToFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un ancien format a été détecté lors de l&apos;analyse du journal de discussion et il est conseillé de le supprimer ainsi que tous les autres scripts qui n&apos;ont pas été mis à jour correctement.
        ///
        ///Souhaitez-vous supprimer ces fichiers?
        ///(Le fichier journal de discussion sera analysé avant la suppression).
        /// </summary>
        internal static string OldChatLog {
            get {
                return ResourceManager.GetString("OldChatLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Souhaitez-vous ouvrir la page de documentation de l&apos;analyseur de journal de discussion disponible sur les forums de GTA World?.
        /// </summary>
        internal static string OpenDocumentation {
            get {
                return ResourceManager.GetString("OpenDocumentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une autre instance est déjà en cours d&apos;exécution, vérifiez votre barre des tâches ou votre gestionnaire de tâches..
        /// </summary>
        internal static string OtherInstanceRunning {
            get {
                return ResourceManager.GetString("OtherInstanceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de l&apos;analyse du journal de discussion..
        /// </summary>
        internal static string ParseError {
            get {
                return ResourceManager.GetString("ParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déplacement des répertoires &quot;{0}&quot; uniquement vers le nouvel emplacement.
        /// </summary>
        internal static string PartialMoveWarning {
            get {
                return ResourceManager.GetString("PartialMoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://github.com/therealoggY/GTAWFrance-Assistant-Chatlog.
        /// </summary>
        internal static string ProjectLink {
            get {
                return ResourceManager.GetString("ProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Question.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://github.com/therealoggY/GTAWFrance-Assistant-Chatlog/releases.
        /// </summary>
        internal static string ReleasesLink {
            get {
                return ResourceManager.GetString("ReleasesLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Redémarrer.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous exécutez la dernière version de l&apos;analyseur du journal de discussion.
        ///
        ///Version installée: {0}.
        /// </summary>
        internal static string RunningLatest {
            get {
                return ResourceManager.GetString("RunningLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le même journal de chat a été sauvegardé {0} ou plusieurs fois, ce qui signifie que le script client RAGEMP responsable de la journalisation de votre chat est interrompu.
        ///
        ///Cela se produit lorsque vous perdez la connexion Internet ou que le serveur se bloque. Le seul moyen connu de résoudre le problème consiste à supprimer les répertoires de ressources du serveur sur lequel vous jouez.
        ///
        ///Les journaux de discussion perdus ne peuvent pas être récupérés..
        /// </summary>
        internal static string SameHashWarning {
            get {
                return ResourceManager.GetString("SameHashWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite lors de la tentative d&apos;enregistrement du fichier..
        /// </summary>
        internal static string SaveError {
            get {
                return ResourceManager.GetString("SaveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à play.gta.world_22007.
        /// </summary>
        internal static string SecondaryIP {
            get {
                return ResourceManager.GetString("SecondaryIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à secondes.
        /// </summary>
        internal static string SecondPlural {
            get {
                return ResourceManager.GetString("SecondPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seconde.
        /// </summary>
        internal static string SecondSingular {
            get {
                return ResourceManager.GetString("SecondSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les paramètres ne seront appliqués qu&apos;une fois que vous aurez fermé la boîte de dialogue des paramètres..
        /// </summary>
        internal static string SettingsAfterClose {
            get {
                return ResourceManager.GetString("SettingsAfterClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filtre simple.
        /// </summary>
        internal static string SimpleFilter {
            get {
                return ResourceManager.GetString("SimpleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Début.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le journal de chat a bien été analysé et sauvegardé sur {0}.
        /// </summary>
        internal static string SuccessfulBackup {
            get {
                return ResourceManager.GetString("SuccessfulBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L&apos;analyseur doit redémarrer pour basculer vers le serveur sélectionné.
        ///
        ///Souhaitez-vous appliquer les modifications et redémarrer l&apos;application maintenant?.
        /// </summary>
        internal static string SwitchServer {
            get {
                return ResourceManager.GetString("SwitchServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à https://ucp-fr.gta.world/.
        /// </summary>
        internal static string UCPLink {
            get {
                return ResourceManager.GetString("UCPLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}..
        /// </summary>
        internal static string UpdateAbortTime {
            get {
                return ResourceManager.GetString("UpdateAbortTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une nouvelle version de l&apos;analyseur de journal de discussion est désormais disponible sur GitHub.
        ///
        ///Version installée: {0}
        ///Version disponible: {1}
        ///
        ///Souhaitez-vous visiter la page des communiqués maintenant?.
        /// </summary>
        internal static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mise à jour disponible.
        /// </summary>
        internal static string UpdateAvailableTitle {
            get {
                return ResourceManager.GetString("UpdateAvailableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}{1}.
        /// </summary>
        internal static string VersionInfo {
            get {
                return ResourceManager.GetString("VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avertissement.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
